sudo: required

dist: trusty

language: python

services:
- docker

before_install:
# Generate SSH key for connection to the docker container
- ssh-keygen -t rsa -N '' -f ssh_key
- cp ssh_key ~/.ssh
- chmod 700 ~/.ssh
- chmod 600 ~/.ssh/ssh_key

# Build the Yunohost docker image
- docker build -t ju/ynh .

# Create and start a docker container from the docker image
- docker create --name yunotest -h docker.yunotest.me -p 22 -p 80:80 -p 443:443 ju/ynh /sbin/init | tee container_id
- export CONTAINER_ID=$(cat container_id)
- docker start ${CONTAINER_ID}

# Setup ssh on host for connection to the docker container
- eval `ssh-agent -s`
- ssh-add ssh_key
- sed -i "s@{{DOCKER_CONTAINER_IP}}@$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' ${CONTAINER_ID})@g" ssh_config
- sed -i "s@{{DOCKER_CONTAINER_SSH_PORT}}@$(docker port ${CONTAINER_ID} 22 | cut -d ':' -f 2)@g" ssh_config
- sed -i "s@{{TRAVIS_HOME}}@${HOME}@g" ssh_config
- cp ssh_config ~/.ssh/config
- cat ~/.ssh/config

# Check connection to the container
- dockerex() { docker exec -i ${CONTAINER_ID} $* ; }
- dockerex ps awxuf
- dockerex hostname -d
- docker exec -i ${CONTAINER_ID} ls -al /root
- docker exec -i ${CONTAINER_ID} ls -al /root/.ssh
- docker exec -i ${CONTAINER_ID} service ssh start
- docker exec -i ${CONTAINER_ID} service cron start
- docker exec -i ${CONTAINER_ID} service rsyslog start
- docker exec -i ${CONTAINER_ID} service dnsmasq start
- docker exec -i ${CONTAINER_ID} service slapd start
- docker exec -i ${CONTAINER_ID} service nscd start
- docker exec -i ${CONTAINER_ID} service nslcd start
- docker exec -i ${CONTAINER_ID} service metronome start
- docker exec -i ${CONTAINER_ID} service nginx start
- docker exec -i ${CONTAINER_ID} service php5-fpm start
- docker exec -i ${CONTAINER_ID} service postfix start
- docker exec -i ${CONTAINER_ID} service dovecot start
- docker exec -i ${CONTAINER_ID} service rspamd start
- docker exec -i ${CONTAINER_ID} service rmilter start
- docker exec -i ${CONTAINER_ID} ps awxuf
- ssh -v ynh ps awxuf || true
- docker exec -i ${CONTAINER_ID} tail -n 100 /var/log/auth.log
- docker exec -i ${CONTAINER_ID} tail -n 100 /var/log/syslog

script:
- sudo ps awxuf
