sudo: required

language: python

services:
- docker

before_install:
# Generate SSH key for connection to the docker container
- ssh-keygen -t rsa -N '' -f ssh_key
- cp ssh_key ~/.ssh
- chmod 700 ~/.ssh
- chmod 600 ~/.ssh/ssh_key

# Build the Yunohost docker image
- docker build -t ju/ynh .

# Create and start a docker container from the docker image
- docker create --name yunotest -h docker.yunotest.me -p 22 -p 80:80 -p 443:443 ju/ynh /sbin/init | tee container_id
- export CONTAINER_ID=$(cat container_id)
- docker start ${CONTAINER_ID}

# Setup ssh on host for connection to the docker container
- eval `ssh-agent -s`
- ssh-add ssh_key
- sed -i "s@{{DOCKER_CONTAINER_IP}}@$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' ${CONTAINER_ID})@g" ssh_config
- sed -i "s@{{DOCKER_CONTAINER_SSH_PORT}}@$(docker port ${CONTAINER_ID} 22 | cut -d ':' -f 2)@g" ssh_config
- sed -i "s@{{TRAVIS_HOME}}@${HOME}@g" ssh_config
- cp ssh_config ~/.ssh/config
- cat ~/.ssh/config

# Check connection to the container
- dockerex() { docker exec -i ${CONTAINER_ID} $* ; }
- dockerex ps awxuf
- dockerex hostname -d
- dockerex ls -al /root
- dockerex ls -al /root/.ssh
- dockerex service ssh start
- dockerex service cron start
- dockerex service rsyslog start
- dockerex service slapd start
- dockerex service nscd start
- dockerex service nslcd start
- dockerex service nginx start
- dockerex service php5-fpm start
#- dockerex service dnsmasq start
#- dockerex service metronome start
#- dockerex service postfix start
#- dockerex service dovecot start
#- dockerex service rspamd start
#- dockerex service rmilter start
- dockerex ps awxuf
- ssh -v ynh ps awxuf || true
- dockerex tail -n 100 /var/log/auth.log
- dockerex tail -n 100 /var/log/syslog

script:
- sudo ps awxuf
