sudo: required

language: python

services:
- docker

git:
  depth: 1

before_install:
- export DOMAIN=docker.yunotest.me

# Generate SSH key for connection to the docker container
- ssh-keygen -t rsa -N '' -f ssh_key
- cp ssh_key ~/.ssh
- chmod 700 ~/.ssh
- chmod 600 ~/.ssh/ssh_key

# Build the Yunohost docker image
- docker build -t ju/ynh .

# Create and start a docker container from the docker image
- docker create --name yunotest -h ${DOMAIN} -p 22 -p 80:80 -p 443:443 ju/ynh /sbin/init | tee container_id
- export CONTAINER_ID=$(cat container_id)
- docker start ${CONTAINER_ID}
- sleep 5
- docker ps
- docker port yunotest

# Setup ssh on host for connection to the docker container
- eval `ssh-agent -s`
- ssh-add ssh_key
#- sed -i "s@{{DOCKER_CONTAINER_IP}}@$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' ${CONTAINER_ID})@g" ssh_config
- sed -i "s@{{DOCKER_CONTAINER_SSH_PORT}}@$(docker port ${CONTAINER_ID} 22 | cut -d ':' -f 2)@g" ssh_config
- sed -i "s@{{TRAVIS_HOME}}@${HOME}@g" ssh_config
- cp ssh_config ~/.ssh/config

# Check connection to the container
- dockerex() { docker exec -i ${CONTAINER_ID} "$@" ; }
- dockerex() { docker exec -i ${CONTAINER_ID} "$@" ; }

- dockerex ps awxuf
- dockerex hostname -d

# Prepare container for ssh connection
- dockerex mkdir /root/.ssh
- dockerex sh -c 'cat > /root/.ssh/authorized_keys' < ssh_key.pub
- dockerex chmod 700 /root/.ssh
- dockerex chmod 600 /root/.ssh/authorized_keys

# Start all services because we have a too simple init in docker
- dockerex service ssh start
- dockerex service cron start
- dockerex service rsyslog start
- dockerex service slapd start
- dockerex service nscd start
- dockerex service nslcd start
- dockerex service nginx start
- dockerex service php5-fpm start
#- dockerex service dnsmasq start
#- dockerex service metronome start
#- dockerex service postfix start
#- dockerex service dovecot start
#- dockerex service rspamd start
#- dockerex service rmilter start
- ssh ynh ps awxuf

# Various hacks for running yunohost in docker container
- bash hacks.sh

# Run yunohost postinstall
- dockerex yunohost tools postinstall --verbose --debug -d ${DOMAIN} -p yunohost --ignore-dyndns
- dockerex ps awxuf
- dockerex cat /var/log/yunohost/yunohost-cli.log

script:
- sudo ps awxuf
- ssh ynh ps awxuf
