sudo: required

language: python

services:
- docker

before_install:
- docker build -t ju/ynh .
- docker create --name yunotest -h yunohost.yunotest-1.nohost.me -p 127.0.0.1:80:80 ju/ynh /sbin/init | tee container_id
- docker ps -a
- docker start $(cat container_id)
- docker ps -a

script:
- docker exec -t $(cat container_id) cat /var/log/yunohost-installation.log
