sudo: required

language: python

services:
- docker

before_install:
- ssh-keygen -t rsa -N ''
- cp ~/.ssh/id_rsa.pub .
- docker build -t ju/ynh .
- docker create --name yunotest -h yunohost.yunotest-1.nohost.me -p 127.0.0.1:80:80 ju/ynh /sbin/init | tee container_id
- docker ps -a
- docker start $(cat container_id)
- sleep 10
- docker ps -a
- docker inspect --format '{{ .NetworkSettings.IPAddress }}' $(cat container_id) | tee container_ip
- ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@$(cat container_ip) ps awxuf

script:
# - docker exec -t $(cat container_id) cat /var/log/yunohost-installation.log
# - docker exec -t $(cat container_id) ps awxuf
- sudo ps awxuf
