#!/bin/bash
set -e

force=$1

function safe_copy () {
    if [[ "$force" == "True" ]]; then
        sudo yunohost service safecopy \
          -s mysql $1 $2 --force
    else
        sudo yunohost service safecopy \
          -s mysql $1 $2
    fi
}

cd /usr/share/yunohost/templates/mysql

if [[ "$(safe_copy my.cnf /etc/mysql/my.cnf | tail -n1)" == "True" ]]; then
    sudo service mysql restart
fi

if [ ! -f /etc/yunohost/mysql ]; then
    [[ $(/bin/ps aux | grep '[m]ysqld') == "0" ]] \
      && sudo service mysql start

    sudo openssl rand -out /etc/yunohost/mysql -base64 16
    sudo chmod 400 /etc/yunohost/mysql

    mysql --no-defaults --user=root --password=yunohost << EOF
USE mysql;
UPDATE user SET password=PASSWORD("$rootpw") WHERE user='root';
FLUSH PRIVILEGES;
EOF

    #sudo aptitude install strace
    #sudo strace mysqladmin --user=root --password=yunohost --protocol=TCP password "$(sudo cat /etc/yunohost/mysql)"
fi

echo "We are here"
